#!/bin/bash
DPU_SETUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $DPU_SETUP_DIR/dpu_config.sh
# Check for git update only argument
git_update_only=false
if [ "$1" == "--git-update-only" ]; then
    git_update_only=true
fi

# Define the folder to clone repositories
target_folder="$DPU_SETUP_DIR/../../dpu_packages"
echo "Cloning repositories in $target_folder"

# Create the target folder if it doesn't exist
if [ ! -d "$target_folder" ]; then
    mkdir -p "$target_folder"
fi

# List Git repositories
git_repos=(
    "https://github.com/spinoza-centre/prfpy_csenf.git"
    "https://github.com/mdaghlian/pycortex.git"
    "https://github.com/mdaghlian/figure_finder.git"
    "https://github.com/mdaghlian/prfpy_bayes.git"
)

# Clone and install each repository in editable mode
for repo in "${git_repos[@]}"; do
    repo_name=$(basename "$repo" .git)
    repo_path="$target_folder/$repo_name"
    
    # Clone the repository if not already cloned
    if [ ! -d "$repo_path" ]; then
        git clone "$repo" "$repo_path"
    else
        # Update the repository if already cloned
        git -C "$repo_path" pull
    fi

    # Skip the installation if the update_only flag is set
    if [ "$git_update_only" = true ]; then
        continue
    fi
    echo "Using $install_cmd to install requirements"
    # Try installing the requirements with mamba or conda
    if [ -f "$repo_path/requirements.txt" ]; then

        $install_cmd "$repo_path/requirements.txt"
    fi
    
    # Install the repository in editable mode
    pip install -e "$repo_path"
done
