#!/usr/bin/env bash
DPU_SETUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $DPU_SETUP_DIR/dpu_config.sh
# Load the config
bash $DPU_SETUP_DIR/dpu_git_install --git-update-only # dpu git update