name: dpu
channels:
  - intel
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alabaster=0.7.12
  - ansi2html=1.8.0
  - appdirs=1.4.4
  - asteval=0.9.27
  - astor=0.8.1
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - atk-1.0=2.36.0
  - attrs=21.4.0
  - babel=2.10.3
  - backcall=0.2.0
  - backports=1.1
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - bleach=5.0.1
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - cairo=1.16.0
  - cffi=1.15.0
  - chardet=4.0.0
  - charset-normalizer=2.1.0
  - ci-info=0.2.0
  - cifti=1.1
  - click=8.1.3
  - clikit=0.6.2
  - cmasher=1.6.3
  - colorama=0.4.4
  - colorspacious=1.1.2
  - comm=0.1.2
  - conda-package-handling=1.8.1
  - crashtest=0.3.1
  - cryptography=41.0.4
  - curl=8.2.1
  - cycler=0.11.0
  - cython=0.29.33
  - dash=2.14.1
  - dbus=1.13.18
  - decorator=5.0.9
  - defusedxml=0.7.1
  - dill=0.3.6
  - docopt=0.6.2
  - docutils=0.18.1
  - double-conversion=3.3.0
  - dpcpp-cpp-rt=2022.1.0
  - dpcpp_cpp_rt=2022.1.0
  - e13tools=0.9.6
  - eigen=3.4.0
  - emcee=3.1.4
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.5.0
  - ffmpeg=4.2.3
  - fftw=3.3.9
  - filelock=3.7.1
  - flask=2.1.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.25.0
  - formulaic=0.3.4
  - fortran_rt=2022.1.0
  - freetype=2.11.0
  - freetype-py=2.3.0
  - fribidi=1.0.10
  - frozenlist=1.3.1
  - future=0.18.2
  - gcc_impl_linux-64=9.5.0
  - gcc_linux-64=9.5.0
  - gdk-pixbuf=2.42.6
  - geos=3.11.2
  - gettext=0.21.1
  - ghostscript=10.03.0
  - giflib=5.2.1
  - gl2ps=1.4.2
  - glew=2.2.0
  - glib=2.78.0
  - glib-tools=2.78.0
  - gmp=6.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - graphviz=2.48.0
  - greenlet=1.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gtk2=2.24.33
  - gts=0.7.6
  - gxx_impl_linux-64=9.5.0
  - gxx_linux-64=9.5.0
  - h5py=3.6.0
  - harfbuzz=2.8.1
  - hdf4=4.2.13
  - hdf5=1.10.6
  - html5lib=1.1
  - httpstan=4.5.0
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=2.10
  - imageio=2.19.3
  - imagemagick=7.1.0_4
  - imagesize=1.4.1
  - impi_rt=2021.6.0
  - importlib-metadata=4.8.1
  - importlib_resources=5.8.0
  - intel-cmplr-lib-rt=2022.1.0
  - intel-cmplr-lic-rt=2022.1.0
  - intel-fortran-rt=2022.1.0
  - intel-opencl-rt=2022.1.0
  - intel-openmp=2022.1.0
  - intelpython=2022.1.0
  - interface_meta=1.3.0
  - ipydatawidgets=4.3.2
  - ipympl=0.9.2
  - ipython=8.10.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - isodate=0.6.1
  - itsdangerous=2.1.2
  - jbig=2.1
  - jcc=3.12
  - jedi=0.18.1
  - jinja2=3.0.1
  - joblib=1.2.0
  - jpeg=9e
  - jsoncpp=1.9.4
  - jsonschema=4.7.2
  - jupyter-dash=0.4.2
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=3.0.5
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kiwisolver=1.3.2
  - kneed=0.7.0
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libarchive=3.5.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libcurl=8.2.1
  - libdeflate=1.12
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgcc-devel_linux-64=9.5.0
  - libgcc-ng=12.1.0
  - libgd=2.3.3
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.78.0
  - libglu=9.0.0
  - libgomp=12.1.0
  - libiconv=1.17
  - libidn2=2.3.3
  - libllvm10=10.0.1
  - libnetcdf=4.8.1
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libogg=1.3.5
  - libpng=1.6.39
  - libpq=12.15
  - librsvg=2.50.7
  - libsanitizer=9.5.0
  - libsodium=1.0.18
  - libsolv=0.7.20
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx-devel_linux-64=9.5.0
  - libstdcxx-ng=12.1.0
  - libtasn1=4.19.0
  - libtheora=1.1.1
  - libtiff=4.4.0
  - libtool=2.4.6
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzip=1.10.1
  - libzlib=1.2.13
  - lmfit=1.0.3
  - loguru=0.7.2
  - looseversion=1.0.1
  - lxml=4.8.0
  - lz4=4.0.0
  - lz4-c=1.9.4
  - lzo=2.10
  - markupsafe=2.0.1
  - marshmallow=3.17.0
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - meshplot=0.4.0
  - mistune=0.8.4
  - mkl=2022.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mkl_umath=0.1.1
  - mplcursors=0.5.1
  - mpldatacursor=0.7.1
  - multidict=6.0.2
  - munkres=1.1.4
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.4.0
  - nbsphinx=0.8.9
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.7.3
  - networkx=2.8.4
  - nibabel=4.0.1
  - nilearn=0.9.1
  - nitime=0.9
  - nspr=4.35
  - nss=3.92
  - num2words=0.5.10
  - numexpr=2.8.1
  - numpy-base=1.21.4
  - olefile=0.46
  - openh264=2.1.1
  - openjdk=8.0.332
  - openjpeg=2.5.0
  - openssl=3.3.0
  - packaging=21.3
  - pandas=1.4.1
  - pandocfilters=1.5.0
  - pango=1.48.7
  - parso=0.8.3
  - pastel=0.2.1
  - patsy=0.5.2
  - pcre=8.45
  - pcre2=10.40
  - perl=5.32.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=21.2.4
  - pixman=0.38.0
  - pkg-config=0.29.2
  - platformdirs=3.10.0
  - ply=3.11
  - pooch=1.7.0
  - proj=6.2.1
  - prompt-toolkit=3.0.30
  - prov=2.0.0
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycairo=1.25.0
  - pycosat=0.6.3
  - pycparser=2.21
  - pydicom=2.3.0
  - pydot=1.4.2
  - pygments=2.12.0
  - pylev=1.4.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.4
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pystan=3.3.0
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python_abi=3.9
  - pythreejs=2.4.2
  - pytz=2022.1
  - pyvista=0.42.2
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.15.9
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - rdflib=6.2.0
  - readline=8.2
  - reportlab=4.0.7
  - reproc=14.2.3
  - reproc-cpp=14.2.3
  - requests=2.25.1
  - rlpycairo=0.2.0
  - ruamel_yaml=0.15.80
  - scikit-learn=1.0.1
  - scooby=0.7.4
  - seaborn=0.11.2
  - setuptools=58.0.4
  - setuptools-scm=7.0.5
  - shapely=2.0.1
  - simplejson=3.17.6
  - sip=6.6.2
  - six=1.16.0
  - snowballstemmer=2.2.0
  - soupsieve=2.3.1
  - sphinx=5.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.42.0
  - stack_data=0.3.0
  - statsmodels=0.13.2
  - svgwrite=1.4.3
  - sysroot_linux-64=2.12
  - tbb=2021.8.0
  - tbb4py=2021.8.0
  - tcl=8.6.10
  - testpath=0.6.0
  - threadpoolctl=2.2.0
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.1
  - tqdm=4.64.1
  - traitlets=5.3.0
  - traits=6.3.2
  - traittypes=0.2.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - uncertainties=3.1.7
  - urllib3=1.26.8
  - utfcpp=3.2.5
  - wand=0.6.10
  - wcwidth=0.2.5
  - webargs=8.2.0
  - webcolors=1.12
  - webencodings=0.5.1
  - werkzeug=2.1.2
  - wget=1.21.4
  - wheel=0.37.1
  - widgetsnbextension=4.0.5
  - wrapt=1.14.1
  - x264=1!152.20180806
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xvfbwrapper=0.2.9
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - about-time==3.1.1
    - alive-progress==2.1.0
    - antspyx==0.3.3
    - apscheduler==3.10.1
    - arrow==1.2.3
    - bids-validator==1.9.9.dev0
    - bokeh==2.2.3
    - brainspace==0.1.4
    - certifi==2022.12.7
    - chart-studio==1.1.0
    - codecarbon==2.1.4
    - debugpy==1.6.3
    - dipy==1.6.0
    - etelemetry==0.3.0
    - fmriprep==23.0.1
    - fracridge==2.0
    - fuzzywuzzy==0.18.0
    - grapheme==0.6.0
    - indexed-gzip==1.7.1
    - ipykernel==6.15.3
    - kaleido==0.2.1
    - llvmlite==0.42.0
    - lockfile==0.12.2
    - mapca==0.0.3
    - neuromaps==0.0.5
    - nighres==1.4.0
    - nipype==1.8.6
    - nitransforms==22.0.0
    - niworkflows==1.7.8
    - numba==0.59.0
    - numpy==1.22.4
    - pipdeptree==2.13.1
    - plotly==5.10.0
    - py-cpuinfo==9.0.0
    - pybids==0.15.3
    - pynvml==11.5.0
    - pysimdjson==3.2.0
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.3.0
    - retrying==1.3.3
    - scikit-image==0.19.3
    - scipy==1.10.1
    - sdcflows==2.4.1
    - sklearn==0.0
    - smriprep==0.11.1
    - sqlalchemy==1.3.24
    - surfplot==0.1.0
    - svgutils==0.3.4
    - tables==3.7.0
    - tedana==0.0.12
    - templateflow==23.0.0
    - tenacity==8.0.1
    - tifffile==2022.8.12
    - toml==0.10.2
    - transforms3d==0.4.1
    - tzdata==2023.3
    - tzlocal==4.3
    - vtk==9.1.0
    - wpca==0.1
    - wslink==1.8.2