name: dpu
channels:
  - intel
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - dash
  - emcee
  - ffmpeg
  - flask
  - h5py
  - hdf4
  - hdf5
  - html5lib
  - imageio
  - intelpython
  - ipydatawidgets
  - ipython
  - ipython_genutils
  - ipywidgets
  - joblib
  - jupyter-dash
  - jupyter_client
  - jupyter_core
  - jupyterlab_pygments
  - jupyterlab_widgets
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mkl_umath
  - mplcursors
  - mpldatacursor
  - nbclient
  - nbconvert
  - nbformat
  - nbsphinx
  - nibabel
  - nilearn
  - nitime
  - numpy-base
  - pandas
  - pandocfilters
  - pickleshare
  - pillow
  - pip
  - pyyaml
  - reportlab
  - scikit-learn
  - seaborn
  - shapely
  - statsmodels
  - widgetsnbextension
  - yaml
  - pip:
    - about-time
    - alive-progress
    - bids-validator
    - bokeh
    - dipy
    - ipykernel
    - kaleido
    - neuromaps
    - nighres
    - nipype
    - nitransforms
    - niworkflows
    - numba
    - numpy
    - plotly
    - pybids
    - scikit-image
    - scipy
    - sklearn
